name: PetSouls
version: 0.1.1
main: org.shadowcrafter.petsouls.PetSouls
author: shadowcrafter
api-version: 1.18

commands:
   welcome:
      description: All you need to know on getting started with PetSouls
      usage: /<command>
   viewrecipe:
      description: View recipes for custom petsoul items
      usage: /<command> <itemkey>
   disablepetsouls:
      description: Enable or disable the PetSouls plugin
      usage: /<command>
   despawnallpets:
      description: Despawn all your pets
      usage: /<command>
   spawnallpets:
      description: Spawn all your pets
      usage: /<command>