name: PetSouls
version: 0.0.1
main: org.shadowcrafter.petsouls.PetSouls
author: shadowcrafter
api-version: 1.18

commands:
   spawn:
      description: spawn pets
   viewrecipe:
      description: View recipes for custom petsoul items
      usage: /<command> <itemkey>